title: Iqbwl
author:
  name: Iqbwl
  email: info@iqbwl.com

url: "https://iqbwl.com"

description: >
  A place for all the random thoughts in my head, a few stories, and notes from whatever Iâ€™m working on.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll_admin:
  hidden_links:
    - datafiles
    - configuration
  homepage: "posts"

show_drafts: true

# front matter
defaults:
  - scope:
      path: ""        # berlaku untuk semua file
      type: "posts"   # atau "pages"
    values:
      layout: "post"
      author: "iqbwl"
      categories: [""]
  - scope:
      path: ""        # untuk semua halaman
      type: "pages"
    values:
      layout: "page"
      author: "iqbwl"

sass:
  quiet_deps: true
  silence_deprecations: [import]

permalink: /:slug

minima:
  skin: classic
  header_pages:
    - about.md
  show_excerpts: true
  date_format: "%Y-%m-%d"
  social_links:
    - title: X
      icon: x-twitter
      url: "https://x.com/iqbwlbit"

    - title: Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/iqbwl.com"

    - title: GitHub
      icon: github
      url: "https://github.com/iqbwl"

    - title: Telegram
      icon: telegram
      url: "https://t.me/iqbwlx"

    - title: Ethereum
      icon: ethereum
      url: "https://etherscan.io/address/iqbwl.eth"

disqus:
  shortname: iqbwl

exclude:
  - .gitignore
  - .jekyll-cache
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - netlify.toml
  - public/
  - serve_dev.sh
  - serve_prod.sh
  - deploy.sh

destination: ./public
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
port: 4000
host: 127.0.0.1
keep_files: [CNAME, .nojekyll]
