title: Iqbwl
author:
  name: Iqbwl
  email: info@iqbwl.com

url: "https://iqbwl.com"

description: >
  A place for all the random thoughts in my head, a few stories, and notes from whatever Iâ€™m working on.

#theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll_admin:
  hidden_links:
    - datafiles
    - configuration
  homepage: "posts"

sass:
  quiet_deps: true
  silence_deprecations: [import]

# Permalink
permalink: /:slug

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  header_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  date_format: "%Y-%m-%d"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/iqbwl"
    - title: X
      icon: x-twitter
      url: "https://x.com/iqbwlbot"
    - title: Telegram
      icon: telegram
      url: "https://t.me/iqbwlx"
    - title: Ethereum
      icon: ethereum
      url: "https://etherscan.io/address/iqbwl.eth"

disqus:
  shortname: iqbwl

exclude:
  - .gitignore
  - .jekyll-cache
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - netlify.toml
  - public/

destination: ./public
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
port: 4000
host: 127.0.0.1
