title: Iqbwl
author:
  name: Iqbwl
  email: iqbwl@iqbwl.com

url: "https://iqbwl.com"

description: >
  Not everything needs a purpose. But hereâ€™s where I keep mine.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll_admin:
  hidden_links:
    - datafiles
    - configuration
  homepage: "posts"

show_drafts: true

# front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "iqbwl"
      categories: [""]
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "iqbwl"

sass:
  quiet_deps: true
  silence_deprecations: [import]

permalink: /:slug

header_pages:
  - about.md

minima:
  skin: auto
  show_excerpts: true
  date_format: "%Y-%m-%d"
  social_links:
    - title: Telegram
      icon: telegram
      url: "https://t.me/iqbwx"

    - title: Ethereum
      icon: ethereum
      url: "https://etherscan.io/address/iqbwl.eth"

disqus:
  shortname: iqbwl

exclude:
  - .gitignore
  - .jekyll-cache
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - netlify.toml
  - public/
  - serve_dev.sh
  - serve_prod.sh
  - deploy.sh

destination: ./public
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
keep_files: [CNAME, .nojekyll]
