[build]
  publish = "public"
  command = "JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_prod.yml"

[[redirects]]
  from = "/archive"
  to = "https://iqbwl.github.io"
  status = 301
  force = true

[[redirects]]
  from = "https://iqbwl.netlify.app/*"
  to = "https://iqbwl.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://iqbwl.com/mangan"
  to = "https://abc.web.id/tools/split-bill"
  status = 301
  force = true
  
